# This file was created automatically with `myst init --gh-pages` 🪄 💚
# Publishes the built MyST site to the gh-pages branch.

name: Build and publish MyST site
on:
  push:
    # Runs on pushes targeting the default branch
    branches: [main]
env:
  # `BASE_URL` determines, relative to the root of the domain, the URL that your site is served from.
  # E.g., if your site lives at `https://mydomain.org/myproject`, set `BASE_URL=/myproject`.
  # If, instead, your site lives at the root of the domain, at `https://mydomain.org`, set `BASE_URL=''`.
  BASE_URL: /${{ github.event.repository.name }}

permissions:
  contents: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install MyST
        run: npm install -g mystmd

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Install LaTeX tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            latexmk \
            texlive-xetex \
            texlive-latex-extra \
            texlive-fonts-recommended \
            fonts-lmodern

      - name: Build PDF
        run: myst build --typst --pdf

      - name: Upload Output PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Output PDF
          path: exports/*.pdf
          compression-level: 0

      - name: Build HTML Assets
        run: myst build --html

      - name: Add .nojekyll
        run: touch _build/html/.nojekyll

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          publish_branch: gh-pages
